### ISSUE TITLE
Identify required microservices

### ISSUE THREAD

**Issue by oakwoodwolf** [Bojo992/CS4337-Project#2]
For the plans of a WhatsApp styled messenger to UL students, we need to identify needed microservices for the architecture. Also identify whether AWS can be used or another service

Acceptance Criteria

- Split requirements for the project into three or more microservices.

**Comment by oakwoodwolf** [comment]
At the moment, the list of microservices that could be used are:

Auth - Google OAuth 2.0
Virtual hosting - AWS EC2 or Azure VM
File Storage - S3
CDN - Amazon CloudFront or Azure Content Delivery Network
	- For sending static content (images)
Caching - AWS Elasticache or Azure Cache for Redis
	- For caching message history on-device
Load Balancing
Database (NoSQL)
X - Lambda
	Used for sending to database

This is free for discussion and I included non AWS alternatives I could find

**Comment by Bojo992** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Identify requierd microservices](https://trello.com/c/CIIzxqTj/3-identify-requierd-microservices)
